Update index.html
bpmn-io/bpmn-js-examples pull request #119
Opened 2020-09-26 08:52 UTC by tuxcell

The </body> tag was missing

__Which issue does this PR address?__

The closing tag </body> was missing therefore I included it.

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/.github/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

2020-09-26 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/bpmn-js-examples?pullRequest=119) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/bpmn-js-examples?pullRequest=119) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/bpmn-js-examples?pullRequest=119) it.</sub>

2020-09-26 13:12 UTC, pinussilvestrus commented
Thanks! Can you update your commit to [fit our message guideline](https://www.conventionalcommits.org/)?

2020-09-28 06:52 UTC, philippfromme requested changes
Thanks for the PR. Let's fix the indentation so we can merge this.

2020-09-28 06:52 UTC, philippfromme commented on properties-panel-extension/app/index.html
> +  </body>
```suggestion
</body>
```

2020-09-28 07:37 UTC, philippfromme commented
Last thing: Let's adjust the commit message to `fix(properties-panel-extension): add closing tag`.

2020-09-29 22:09 UTC, tuxcell commented
> Last thing: Let's adjust the commit message to `fix(properties-panel-extension): add closing tag`.

Done

2020-09-30 05:59 UTC, pinussilvestrus commented
Your commit message(s) still have the wrong format: https://github.com/bpmn-io/bpmn-js-examples/pull/119/commits. Also, please [squash them together](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) to one single commit.

2020-10-05 07:27 UTC, closed without merging